### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#119]
I attached a picture of what I would like the home screen to look like and it also gives a better look at how I want the sign-up form to look like, the changes include:

Heading text italicized and a little smaller to match the width of the video

a semi-transparant line going across the sceen below the video including the sign up form

And below all of that a "OR CLICK HERE TO SIGN UP NOW" link, this link will take the new user to a new page were they would be able to pay and sign up without going through the "FREE TRIAL" process, this page would ask for their email address and would look like the Upgrade page, where they could choose a plan and enter payment information....

This new page is also were they would be directed when they click on the "Pricing" table near the bottom of the home screen, which I will elaberate on more in the future
![30day](https://cloud.githubusercontent.com/assets/10223970/7040180/c7978200-dd91-11e4-9d6a-58dda0a4e44d.png)

**Comment by invokelocal** [comment]
In the text above I used the wrong words for the sing up now link, the text for that link should be as it is in the picture, and it should say "OR CLICK HERE TO BUY NOW"

**Comment by invokelocal** [comment]
the "OR CLICK HERE TO BUY NOW" link would go to:

http://revucue.com/user/create

that you already have set up

**Comment by invokelocal** [comment]
For the form field and graphics that say : 

"PLEASE ENTER YOUR EMAIL ADDRESS" & "START YOUR 30 DAY TRIAL"

this graphic can look a little different than the png I provided if you need to change it to display well on phones, tablet, and pc's....

**Comment by orientationsys** [comment]
Done ! Please check.

**Comment by invokelocal** [comment]
on the form button you have "START YOUR 30 DAY TRIAL" CAN YOU MAKE IT SAY:

"START YOUR 30 DAY FREE TRIAL"

and everything is looking good on all devices but as the screen size gets bigger the email form / button and the Buy Now link start to move to the left of center

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
The spelling is good, but the form is still too much to the left on larger screens, can you fix it to stay centered and still look goog on mobile phones?

**Comment by invokelocal** [comment]
![left](https://cloud.githubusercontent.com/assets/10223970/7080587/514290bc-defa-11e4-9f55-3f68849a67d4.png)

**Comment by orientationsys** [comment]
I have made a change the template, so what about now ??

**Comment by invokelocal** [comment]
It is looking better, but the words on the button are still wrong.....

It now says: "START YOUR 30 FREE TRIAL"

it should say: "START YOUR 30 DAY FREE TRIAL"

**Comment by invokelocal** [comment]
make "START YOUR 30 DAY FREE TRIAL" bold type font

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Now the button is too small for the text that is on the button.....

**Comment by orientationsys** [comment]
Done ! Please check.

**Comment by invokelocal** [comment]
DONE!!!!!
