### ISSUE TITLE
Track Company Rate Percentage

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#130]
On every portal dashboard the pie chart that tracks Total Customers and the "Rated %" I would like to track this "Rated" % for the company as a whole from within intercom.io, and I would like this data to show up on the main table of the intercom dashboard as you have other data there...

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
For some reason the data is not showing up in intercom as of right now.... Also in the "Phone Number" column this data is not showing up in intercom dashboard correctly either

**Comment by invokelocal** [comment]
**the new rate % data is the data I was referring to in the last comment

**Comment by orientationsys** [comment]
What about now? I have added the Phone Number

**Comment by invokelocal** [comment]
It is still the same, no sign of the rate% and the phone number data is empty on all but 1 row.....

Your log into intercom should still work so go in there and change anything that is needed to make the integration work

**Comment by invokelocal** [comment]
Maybe you should push the phone number from revucue to stripe.com as this would be useful information within stripe and stripe sends all this info automatically to intercom... but you would still have to code the rate% directly to intercom
